Coderevert_map_withsymbol = {'Alanine aminotransferase increased': [('ALT', '+')],
 'Amylase increased': [('AMYLASE', '+')],
 'Anaemia': [('HGB', '-'), ('RBC', '-')],
 'Aspartate aminotransferase increased': [('AST', '+')],
 'Basophil count increased': [('BASO', '+')],
 'Basophilopenia': [('BASO', '-')],
 'Bilirubin conjugated increased': [('BILDIR', '+')],
 'Blood albumin decreased': [('ALB', '-')],
 'Blood alkaline phosphatase increased': [('ALP', '+')],
 'Blood bilirubin increased': [('BILI', '+')],
 'Blood calcium decreased': [('CA', '-')],
 'Blood calcium increased': [('CA', '+')],
 'Blood chloride decreased': [('CL', '-')],
 'Blood creatine phosphokinase increased': [('CK', '+')],
 'Blood creatinine increased': [('CREAT', '+')],
 'Blood glucose increased': [('GLUC_FAST', '+')],
 'Blood lactate dehydrogenase increased': [('LDH', '+')],
 'Blood magnesium decreased': [('MG', '-')],
 'Blood phosphorus decreased': [('PHOS', '-')],
 'Blood phosphorus increased': [('PHOS', '+')],
 'Blood potassium decreased': [('K', '-')],
 'Blood potassium increased': [('K', '+')],
 'Blood sodium decreased': [('SODIUM', '-')],
 'Blood thyroid stimulating hormone decreased': [('TSH', '-')],
 'Blood thyroid stimulating hormone increased': [('TSH', '+')],
 'Blood urea decreased': [('UREAN', '-')],
 'Blood urea increased': [('UREA', '+'), ('UREAN', '+')],
 'C-reactive protein increased': [('CRP', '+')],
 'Calcium ionised decreased': [('CA', '-')],
 'Creatine kinase MB increased': [('CKMB', '+')],
 'Eosinophil count decreased': [('EOS', '-')],
 'Eosinophil count increased': [('EOS', '+')],
 'Gamma-glutamyltransferase increased': [('GGT', '+')],
 'Haematocrit decreased': [('HCT', '-')],
 'Hypercalcaemia': [('CA', '+')],
 'Hyperchloraemia': [('CL', '+')],
 'Hyperglycaemia': [('GLUC_FAST', '+')],
 'Hyperkalaemia': [('K', '+')],
 'Hypermagnesaemia': [('MG', '+')],
 'Hypernatraemia': [('SODIUM', '+')],
 'Hyperphosphataemia': [('PHOS', '+')],
 'Hypoalbuminaemia': [('ALB', '-')],
 'Hypocalcaemia': [('CA', '-')],
 'Hypochloraemia': [('CL', '-')],
 'Hypoglycaemia': [('GLUC_FAST', '-')],
 'Hypokalaemia': [('K', '-')],
 'Hypomagnesaemia': [('MG', '-')],
 'Hyponatraemia': [('SODIUM', '-')],
 'Hypophosphataemia': [('PHOS', '-')],
 'International normalised ratio increased': [('INR', '+')],
 'Lymphocyte count decreased': [('LYM', '-'), ('MONO', '-')],
 'Lymphocyte count increased': [('LYM', '+')],
 'Monocyte count increased': [('MONO', '+')],
 'Monocyte percentage increased': [('MONO', '+')],
 'Neutrophil count decreased': [('NEUT', '-')],
 'Neutrophil count increased': [('NEUT', '+')],
 'Platelet count decreased': [('PLAT', '-')],
 'Platelet count increased': [('PLAT', '+')],
 'Protein total decreased': [('PROT', '-')],
 'Prothrombin time prolonged': [('PT', '+')],
 'Red blood cell count decreased': [('RBC', '-')],
 'Thrombocytopenia': [('PLAT', '-')],
 'Thyroxine free decreased': [('T4FR', '-')],
 'Thyroxine free increased': [('T4FR', '+')],
 'Tri-iodothyronine decreased': [('T3', '-')],
 'Tri-iodothyronine free decreased': [('T3FR', '-')],
 'Tri-iodothyronine free increased': [('T3FR', '+')],
 'White blood cell count decreased': [('WBC', '-')],
 'White blood cell count increased': [('WBC', '+')]}

Coderevert_map_nosymbol = {('Alanine aminotransferase increased',): ['ALT'],
 ('Amylase increased',): ['AMYLASE'],
 ('Anaemia', 'Red blood cell count decreased'): ['HGB', 'RBC'],
 ('Aspartate aminotransferase increased',): ['AST'],
 ('Basophil count increased', 'Basophilopenia'): ['BASO'],
 ('Bilirubin conjugated increased',): ['BILDIR'],
 ('Blood albumin decreased', 'Hypoalbuminaemia'): ['ALB'],
 ('Blood alkaline phosphatase increased',): ['ALP'],
 ('Blood bilirubin increased',): ['BILI'],
 ('Blood calcium decreased', 'Blood calcium increased', 'Calcium ionised decreased', 'Hypercalcaemia', 'Hypocalcaemia'): ['CA'],
 ('Blood chloride decreased', 'Hyperchloraemia', 'Hypochloraemia'): ['CL'],
 ('Blood creatine phosphokinase increased',): ['CK'],
 ('Blood creatinine increased',): ['CREAT'],
 ('Blood glucose increased', 'Hyperglycaemia', 'Hypoglycaemia'): ['GLUC_FAST'],
 ('Blood lactate dehydrogenase increased',): ['LDH'],
 ('Blood magnesium decreased', 'Hypermagnesaemia', 'Hypomagnesaemia'): ['MG'],
 ('Blood phosphorus decreased', 'Blood phosphorus increased', 'Hyperphosphataemia', 'Hypophosphataemia'): ['PHOS'],
 ('Blood potassium decreased', 'Blood potassium increased', 'Hyperkalaemia', 'Hypokalaemia'): ['K'],
 ('Blood sodium decreased', 'Hypernatraemia', 'Hyponatraemia'): ['SODIUM'],
 ('Blood thyroid stimulating hormone decreased', 'Blood thyroid stimulating hormone increased'): ['TSH'],
 ('Blood urea decreased', 'Blood urea increased'): ['UREA', 'UREAN'],
 ('C-reactive protein increased',): ['CRP'],
 ('Creatine kinase MB increased',): ['CKMB'],
 ('Eosinophil count decreased', 'Eosinophil count increased'): ['EOS'],
 ('Gamma-glutamyltransferase increased',): ['GGT'],
 ('Haematocrit decreased',): ['HCT'],
 ('International normalised ratio increased',): ['INR'],
 ('Lymphocyte count decreased', 'Lymphocyte count increased'): ['LYM'],
 ('Lymphocyte count decreased', 'Lymphocyte count increased', 'Monocyte count increased', 'Monocyte percentage increased'): ['LYM',
                                                                                                                             'MONO'],
 ('Lymphocyte count decreased', 'Monocyte count increased', 'Monocyte percentage increased'): ['MONO'],
 ('Neutrophil count decreased', 'Neutrophil count increased'): ['NEUT'],
 ('Platelet count decreased', 'Platelet count increased', 'Thrombocytopenia'): ['PLAT'],
 ('Protein total decreased',): ['PROT'],
 ('Prothrombin time prolonged',): ['PT'],
 ('Thyroxine free decreased', 'Thyroxine free increased'): ['T4FR'],
 ('Tri-iodothyronine decreased',): ['T3'],
 ('Tri-iodothyronine free decreased', 'Tri-iodothyronine free increased'): ['T3FR'],
 ('White blood cell count decreased', 'White blood cell count increased'): ['WBC']}

