Codelist_map = {('ALB', '-'): ['Hypoalbuminaemia', 'Blood albumin decreased'],
 ('ALP', '+'): ['Blood alkaline phosphatase increased'],
 ('ALT', '+'): ['Alanine aminotransferase increased'],
 ('AMYLASE', '+'): ['Amylase increased'],
 ('AST', '+'): ['Aspartate aminotransferase increased'],
 ('BASO', '+'): ['Basophil count increased'],
 ('BASO', '-'): ['Basophilopenia'],
 ('BILDIR', '+'): ['Bilirubin conjugated increased'],
 ('BILI', '+'): ['Blood bilirubin increased'],
 ('CA', '+'): ['Blood calcium increased', 'Hypercalcaemia'],
 ('CA', '-'): ['Blood calcium decreased',
               'Calcium ionised decreased',
               'Hypocalcaemia'],
 ('CK', '+'): ['Blood creatine phosphokinase increased'],
 ('CKMB', '+'): ['Creatine kinase MB increased'],
 ('CL', '+'): ['Hyperchloraemia'],
 ('CL', '-'): ['Hypochloraemia', 'Blood chloride decreased'],
 ('CREAT', '+'): ['Blood creatinine increased'],
 ('CRP', '+'): ['C-reactive protein increased'],
 ('EOS', '+'): ['Eosinophil count increased'],
 ('EOS', '-'): ['Eosinophil count decreased'],
 ('GGT', '+'): ['Gamma-glutamyltransferase increased'],
 ('GLUC_FAST', '+'): ['Hyperglycaemia', 'Blood glucose increased'],
 ('GLUC_FAST', '-'): ['Hypoglycaemia'],
 ('HCT', '-'): ['Haematocrit decreased'],
 ('HGB', '-'): ['Anaemia'],
 ('INR', '+'): ['International normalised ratio increased'],
 ('K', '+'): ['Hyperkalaemia', 'Blood potassium increased'],
 ('K', '-'): ['Hypokalaemia', 'Blood potassium decreased'],
 ('LDH', '+'): ['Blood lactate dehydrogenase increased'],
 ('LYM', '+'): ['Lymphocyte count increased'],
 ('LYM', '-'): ['Lymphocyte count decreased'],
 ('MG', '+'): ['Hypermagnesaemia'],
 ('MG', '-'): ['Hypomagnesaemia', 'Blood magnesium decreased'],
 ('MONO', '+'): ['Monocyte count increased', 'Monocyte percentage increased'],
 ('MONO', '-'): ['Lymphocyte count decreased'],
 ('NEUT', '+'): ['Neutrophil count increased'],
 ('NEUT', '-'): ['Neutrophil count decreased'],
 ('PHOS', '+'): ['Blood phosphorus increased', 'Hyperphosphataemia'],
 ('PHOS', '-'): ['Hypophosphataemia', 'Blood phosphorus decreased'],
 ('PLAT', '+'): ['Platelet count increased'],
 ('PLAT', '-'): ['Platelet count decreased', 'Thrombocytopenia'],
 ('PROT', '-'): ['Protein total decreased'],
 ('PT', '+'): ['Prothrombin time prolonged'],
 ('RBC', '-'): ['Red blood cell count decreased', 'Anaemia'],
 ('SODIUM', '+'): ['Hypernatraemia'],
 ('SODIUM', '-'): ['Hyponatraemia', 'Blood sodium decreased'],
 ('T3', '-'): ['Tri-iodothyronine decreased'],
 ('T3FR', '+'): ['Tri-iodothyronine free increased'],
 ('T3FR', '-'): ['Tri-iodothyronine free decreased'],
 ('T4FR', '+'): ['Thyroxine free increased'],
 ('T4FR', '-'): ['Thyroxine free decreased'],
 ('TSH', '+'): ['Blood thyroid stimulating hormone increased'],
 ('TSH', '-'): ['Blood thyroid stimulating hormone decreased'],
 ('UREA', '+'): ['Blood urea increased'],
 ('UREAN', '+'): ['Blood urea increased'],
 ('UREAN', '-'): ['Blood urea decreased'],
 ('WBC', '+'): ['White blood cell count increased'],
 ('WBC', '-'): ['White blood cell count decreased']}