Codelist_map = {('ALB', '-'): ['Hypoalbuminaemia', 'Blood albumin decreased'],
 ('ALP', '+'): ['Blood alkaline phosphatase increased'],
 ('ALT', '+'): ['Alanine aminotransferase increased'],
 ('AMYLASE', '+'): ['Amylase increased'],
 ('AST', '+'): ['Aspartate aminotransferase increased'],
 ('BASO', '+'): ['Basophil count increased', 'Basophilopenia'],
 ('BASO', '-'): ['Basophilopenia'],
 ('BILDIR', '+'): ['Bilirubin conjugated increased'],
 ('BILI', '+'): ['Blood bilirubin increased'],
 ('CA', '+'): ['Blood calcium increased',
               'Hypercalcaemia',
               'Blood calcium decreased',
               'Calcium ionised decreased',
               'Hypocalcaemia'],
 ('CA', '-'): ['Blood calcium decreased',
               'Calcium ionised decreased',
               'Hypocalcaemia'],
 ('CK', '+'): ['Blood creatine phosphokinase increased'],
 ('CKMB', '+'): ['Creatine kinase MB increased'],
 ('CL', '+'): ['Hyperchloraemia', 'Hypochloraemia', 'Blood chloride decreased'],
 ('CL', '-'): ['Hypochloraemia', 'Blood chloride decreased'],
 ('CREAT', '+'): ['Blood creatinine increased'],
 ('CRP', '+'): ['C-reactive protein increased'],
 ('EOS', '+'): ['Eosinophil count increased', 'Eosinophil count decreased'],
 ('EOS', '-'): ['Eosinophil count decreased'],
 ('GGT', '+'): ['Gamma-glutamyltransferase increased'],
 ('GLUC_FAST', '+'): ['Hyperglycaemia',
                      'Blood glucose increased',
                      'Hypoglycaemia'],
 ('GLUC_FAST', '-'): ['Hypoglycaemia'],
 ('HCT', '-'): ['Haematocrit decreased'],
 ('HGB', '-'): ['Anaemia'],
 ('INR', '+'): ['International normalised ratio increased'],
 ('K', '+'): ['Hyperkalaemia',
              'Blood potassium increased',
              'Hypokalaemia',
              'Blood potassium decreased'],
 ('K', '-'): ['Hypokalaemia', 'Blood potassium decreased'],
 ('LDH', '+'): ['Blood lactate dehydrogenase increased'],
 ('LYM', '+'): ['Lymphocyte count increased', 'Lymphocyte count decreased'],
 ('LYM', '-'): ['Lymphocyte count decreased'],
 ('MG', '+'): ['Hypermagnesaemia',
               'Hypomagnesaemia',
               'Blood magnesium decreased'],
 ('MG', '-'): ['Hypomagnesaemia', 'Blood magnesium decreased'],
 ('MONO', '+'): ['Monocyte count increased',
                 'Monocyte percentage increased',
                 'Lymphocyte count decreased'],
 ('MONO', '-'): ['Lymphocyte count decreased'],
 ('NEUT', '+'): ['Neutrophil count increased', 'Neutrophil count decreased'],
 ('NEUT', '-'): ['Neutrophil count decreased'],
 ('PHOS', '+'): ['Blood phosphorus increased',
                 'Hyperphosphataemia',
                 'Hypophosphataemia',
                 'Blood phosphorus decreased'],
 ('PHOS', '-'): ['Hypophosphataemia', 'Blood phosphorus decreased'],
 ('PLAT', '+'): ['Platelet count increased',
                 'Platelet count decreased',
                 'Thrombocytopenia'],
 ('PLAT', '-'): ['Platelet count decreased', 'Thrombocytopenia'],
 ('PROT', '-'): ['Protein total decreased'],
 ('PT', '+'): ['Prothrombin time prolonged'],
 ('RBC', '-'): ['Red blood cell count decreased', 'Anaemia'],
 ('SODIUM', '+'): ['Hypernatraemia', 'Hyponatraemia', 'Blood sodium decreased'],
 ('SODIUM', '-'): ['Hyponatraemia', 'Blood sodium decreased'],
 ('T3', '-'): ['Tri-iodothyronine decreased'],
 ('T3FR', '+'): ['Tri-iodothyronine free increased',
                 'Tri-iodothyronine free decreased'],
 ('T3FR', '-'): ['Tri-iodothyronine free decreased'],
 ('T4FR', '+'): ['Thyroxine free increased', 'Thyroxine free decreased'],
 ('T4FR', '-'): ['Thyroxine free decreased'],
 ('TSH', '+'): ['Blood thyroid stimulating hormone increased',
                'Blood thyroid stimulating hormone decreased'],
 ('TSH', '-'): ['Blood thyroid stimulating hormone decreased'],
 ('UREA', '+'): ['Blood urea increased'],
 ('UREAN', '+'): ['Blood urea increased', 'Blood urea decreased'],
 ('UREAN', '-'): ['Blood urea decreased'],
 ('WBC', '+'): ['White blood cell count increased',
                'White blood cell count decreased'],
 ('WBC', '-'): ['White blood cell count decreased']}

Codelist_map_plus = {'ALP': ['Blood alkaline phosphatase increased'],
 'ALT': ['Alanine aminotransferase increased'],
 'AMYLASE': ['Amylase increased'],
 'AST': ['Aspartate aminotransferase increased'],
 'BASO': ['Basophil count increased', 'Basophilopenia'],
 'BILDIR': ['Bilirubin conjugated increased'],
 'BILI': ['Blood bilirubin increased'],
 'CA': ['Blood calcium increased',
        'Hypercalcaemia',
        'Blood calcium decreased',
        'Calcium ionised decreased',
        'Hypocalcaemia'],
 'CK': ['Blood creatine phosphokinase increased'],
 'CKMB': ['Creatine kinase MB increased'],
 'CL': ['Hyperchloraemia', 'Hypochloraemia', 'Blood chloride decreased'],
 'CREAT': ['Blood creatinine increased'],
 'CRP': ['C-reactive protein increased'],
 'EOS': ['Eosinophil count increased', 'Eosinophil count decreased'],
 'GGT': ['Gamma-glutamyltransferase increased'],
 'GLUC_FAST': ['Hyperglycaemia', 'Blood glucose increased', 'Hypoglycaemia'],
 'INR': ['International normalised ratio increased'],
 'K': ['Hyperkalaemia',
       'Blood potassium increased',
       'Hypokalaemia',
       'Blood potassium decreased'],
 'LDH': ['Blood lactate dehydrogenase increased'],
 'LYM': ['Lymphocyte count increased', 'Lymphocyte count decreased'],
 'MG': ['Hypermagnesaemia', 'Hypomagnesaemia', 'Blood magnesium decreased'],
 'MONO': ['Monocyte count increased',
          'Monocyte percentage increased',
          'Lymphocyte count decreased'],
 'NEUT': ['Neutrophil count increased', 'Neutrophil count decreased'],
 'PHOS': ['Blood phosphorus increased',
          'Hyperphosphataemia',
          'Hypophosphataemia',
          'Blood phosphorus decreased'],
 'PLAT': ['Platelet count increased',
          'Platelet count decreased',
          'Thrombocytopenia'],
 'PT': ['Prothrombin time prolonged'],
 'SODIUM': ['Hypernatraemia', 'Hyponatraemia', 'Blood sodium decreased'],
 'T3FR': ['Tri-iodothyronine free increased',
          'Tri-iodothyronine free decreased'],
 'T4FR': ['Thyroxine free increased', 'Thyroxine free decreased'],
 'TSH': ['Blood thyroid stimulating hormone increased',
         'Blood thyroid stimulating hormone decreased'],
 'UREA': ['Blood urea increased'],
 'UREAN': ['Blood urea increased', 'Blood urea decreased'],
 'WBC': ['White blood cell count increased',
         'White blood cell count decreased']}

Codelist_map_minus = {'ALB': ['Hypoalbuminaemia', 'Blood albumin decreased'],
 'BASO': ['Basophilopenia'],
 'CA': ['Blood calcium decreased',
        'Calcium ionised decreased',
        'Hypocalcaemia'],
 'CL': ['Hypochloraemia', 'Blood chloride decreased'],
 'EOS': ['Eosinophil count decreased'],
 'GLUC_FAST': ['Hypoglycaemia'],
 'HCT': ['Haematocrit decreased'],
 'HGB': ['Anaemia'],
 'K': ['Hypokalaemia', 'Blood potassium decreased'],
 'LYM': ['Lymphocyte count decreased'],
 'MG': ['Hypomagnesaemia', 'Blood magnesium decreased'],
 'MONO': ['Lymphocyte count decreased'],
 'NEUT': ['Neutrophil count decreased'],
 'PHOS': ['Hypophosphataemia', 'Blood phosphorus decreased'],
 'PLAT': ['Platelet count decreased', 'Thrombocytopenia'],
 'PROT': ['Protein total decreased'],
 'RBC': ['Red blood cell count decreased', 'Anaemia'],
 'SODIUM': ['Hyponatraemia', 'Blood sodium decreased'],
 'T3': ['Tri-iodothyronine decreased'],
 'T3FR': ['Tri-iodothyronine free decreased'],
 'T4FR': ['Thyroxine free decreased'],
 'TSH': ['Blood thyroid stimulating hormone decreased'],
 'UREAN': ['Blood urea decreased'],
 'WBC': ['White blood cell count decreased']}

Codelist_map_nosymbol = {'ALB': ['Hypoalbuminaemia', 'Blood albumin decreased'],
 'ALP': ['Blood alkaline phosphatase increased'],
 'ALT': ['Alanine aminotransferase increased'],
 'AMYLASE': ['Amylase increased'],
 'AST': ['Aspartate aminotransferase increased'],
 'BASO': ['Basophil count increased', 'Basophilopenia'],
 'BILDIR': ['Bilirubin conjugated increased'],
 'BILI': ['Blood bilirubin increased'],
 'CA': ['Blood calcium increased',
        'Hypercalcaemia',
        'Blood calcium decreased',
        'Calcium ionised decreased',
        'Hypocalcaemia'],
 'CK': ['Blood creatine phosphokinase increased'],
 'CKMB': ['Creatine kinase MB increased'],
 'CL': ['Hyperchloraemia', 'Hypochloraemia', 'Blood chloride decreased'],
 'CREAT': ['Blood creatinine increased'],
 'CRP': ['C-reactive protein increased'],
 'EOS': ['Eosinophil count increased', 'Eosinophil count decreased'],
 'GGT': ['Gamma-glutamyltransferase increased'],
 'GLUC_FAST': ['Hyperglycaemia', 'Blood glucose increased', 'Hypoglycaemia'],
 'HCT': ['Haematocrit decreased'],
 'HGB': ['Anaemia'],
 'INR': ['International normalised ratio increased'],
 'K': ['Hyperkalaemia',
       'Blood potassium increased',
       'Hypokalaemia',
       'Blood potassium decreased'],
 'LDH': ['Blood lactate dehydrogenase increased'],
 'LYM': ['Lymphocyte count increased', 'Lymphocyte count decreased'],
 'MG': ['Hypermagnesaemia', 'Hypomagnesaemia', 'Blood magnesium decreased'],
 'MONO': ['Monocyte count increased',
          'Monocyte percentage increased',
          'Lymphocyte count decreased'],
 'NEUT': ['Neutrophil count increased', 'Neutrophil count decreased'],
 'PHOS': ['Blood phosphorus increased',
          'Hyperphosphataemia',
          'Hypophosphataemia',
          'Blood phosphorus decreased'],
 'PLAT': ['Platelet count increased',
          'Platelet count decreased',
          'Thrombocytopenia'],
 'PROT': ['Protein total decreased'],
 'PT': ['Prothrombin time prolonged'],
 'RBC': ['Red blood cell count decreased', 'Anaemia'],
 'SODIUM': ['Hypernatraemia', 'Hyponatraemia', 'Blood sodium decreased'],
 'T3': ['Tri-iodothyronine decreased'],
 'T3FR': ['Tri-iodothyronine free increased',
          'Tri-iodothyronine free decreased'],
 'T4FR': ['Thyroxine free increased', 'Thyroxine free decreased'],
 'TSH': ['Blood thyroid stimulating hormone increased',
         'Blood thyroid stimulating hormone decreased'],
 'UREA': ['Blood urea increased'],
 'UREAN': ['Blood urea increased', 'Blood urea decreased'],
 'WBC': ['White blood cell count increased',
         'White blood cell count decreased']}

