Coderevert_map = {'Alanine aminotransferase increased': [('ALT', '+')],
 'Amylase increased': [('AMYLASE', '+')],
 'Anaemia': [('HGB', '-'), ('RBC', '-')],
 'Aspartate aminotransferase increased': [('AST', '+')],
 'Basophil count increased': [('BASO', '+')],
 'Basophilopenia': [('BASO', '-')],
 'Bilirubin conjugated increased': [('BILDIR', '+')],
 'Blood albumin decreased': [('ALB', '-')],
 'Blood alkaline phosphatase increased': [('ALP', '+')],
 'Blood bilirubin increased': [('BILI', '+')],
 'Blood calcium decreased': [('CA', '-')],
 'Blood calcium increased': [('CA', '+')],
 'Blood chloride decreased': [('CL', '-')],
 'Blood creatine phosphokinase increased': [('CK', '+')],
 'Blood creatinine increased': [('CREAT', '+')],
 'Blood glucose increased': [('GLUC_FAST', '+')],
 'Blood lactate dehydrogenase increased': [('LDH', '+')],
 'Blood magnesium decreased': [('MG', '-')],
 'Blood phosphorus decreased': [('PHOS', '-')],
 'Blood phosphorus increased': [('PHOS', '+')],
 'Blood potassium decreased': [('K', '-')],
 'Blood potassium increased': [('K', '+')],
 'Blood sodium decreased': [('SODIUM', '-')],
 'Blood thyroid stimulating hormone decreased': [('TSH', '-')],
 'Blood thyroid stimulating hormone increased': [('TSH', '+')],
 'Blood urea decreased': [('UREAN', '-')],
 'Blood urea increased': [('UREA', '+'), ('UREAN', '+')],
 'C-reactive protein increased': [('CRP', '+')],
 'Calcium ionised decreased': [('CA', '-')],
 'Creatine kinase MB increased': [('CKMB', '+')],
 'Eosinophil count decreased': [('EOS', '-')],
 'Eosinophil count increased': [('EOS', '+')],
 'Gamma-glutamyltransferase increased': [('GGT', '+')],
 'Haematocrit decreased': [('HCT', '-')],
 'Hypercalcaemia': [('CA', '+')],
 'Hyperchloraemia': [('CL', '+')],
 'Hyperglycaemia': [('GLUC_FAST', '+')],
 'Hyperkalaemia': [('K', '+')],
 'Hypermagnesaemia': [('MG', '+')],
 'Hypernatraemia': [('SODIUM', '+')],
 'Hyperphosphataemia': [('PHOS', '+')],
 'Hypoalbuminaemia': [('ALB', '-')],
 'Hypocalcaemia': [('CA', '-')],
 'Hypochloraemia': [('CL', '-')],
 'Hypoglycaemia': [('GLUC_FAST', '-')],
 'Hypokalaemia': [('K', '-')],
 'Hypomagnesaemia': [('MG', '-')],
 'Hyponatraemia': [('SODIUM', '-')],
 'Hypophosphataemia': [('PHOS', '-')],
 'International normalised ratio increased': [('INR', '+')],
 'Lymphocyte count decreased': [('LYM', '-'), ('MONO', '-')],
 'Lymphocyte count increased': [('LYM', '+')],
 'Monocyte count increased': [('MONO', '+')],
 'Monocyte percentage increased': [('MONO', '+')],
 'Neutrophil count decreased': [('NEUT', '-')],
 'Neutrophil count increased': [('NEUT', '+')],
 'Platelet count decreased': [('PLAT', '-')],
 'Platelet count increased': [('PLAT', '+')],
 'Protein total decreased': [('PROT', '-')],
 'Prothrombin time prolonged': [('PT', '+')],
 'Red blood cell count decreased': [('RBC', '-')],
 'Thrombocytopenia': [('PLAT', '-')],
 'Thyroxine free decreased': [('T4FR', '-')],
 'Thyroxine free increased': [('T4FR', '+')],
 'Tri-iodothyronine decreased': [('T3', '-')],
 'Tri-iodothyronine free decreased': [('T3FR', '-')],
 'Tri-iodothyronine free increased': [('T3FR', '+')],
 'White blood cell count decreased': [('WBC', '-')],
 'White blood cell count increased': [('WBC', '+')]}